mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456

php:
  build: ./php
  ports:
    - "9000:9000"
  links:
    - "mysql"
  volumes:
    - ~/home/var/www:/var/www

nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - ~/home/var/www:/var/www

redis:
  build: ./redis
  ports:
    - "6379:6379"